### ISSUE TITLE
Saber not connecting

### ISSUE THREAD

**Issue by JediiKnyght** [Nuntis-Spayz/gilthoniel#15]
Hello

I am using the software on WIndows 10 as an Administrator, and the 'saber is connecting to the computer (evidenced by flashing blade, Windows 'connecting' sound and the Com Port appearing in the app... yet it won't 'connect' for me to make any changes. Am I missing a step, somewhere?

This is all the Log says when trying to connect:

-----------------
Opening COM3
Port Open
>> V?
-----------------

**Comment by Nuntis-Spayz** [comment]
I suspect it is either an early firmware that has no PC communication, or an original Anima which does not work with gilthoniel.

**Comment by GuitoonDev** [comment]
Hi !

I have just the same problem like JediiKnyght. The anima is recognized by windows (COM4), it appears in connected devices, the serial port is displayed in Gilthoniel but it can't connect with the saber :

![Capture d’écran 2021-09-24 214125](https://user-images.githubusercontent.com/32094695/134731240-1c3d5ed8-ca7c-436c-8c2c-769264d4a314.png)

I bought my saber in 2020 so I guess it's a recent Anima EVO version.

Do you still recommend to updating the firmware or maybe I have to do something else ? ^^'

**Comment by Nuntis-Spayz** [comment]
@GuitoonDev
> I bought my saber in 2020 so I guess it's a recent Anima EVO version.

The early Anima Evo firmware did not talk to computers - so when the debug log sends V? to the saber and gets no response that indicates it is the very earlist firmware (or that it is an original Anima)

So
1) Double check that it is an Anima EVO - the EVO has an on/off switch on the outside - the original Anima has two small switches inside the pommel.
2) YES - upgrade the firmware

Per Gilthoniel website
> Gilthoniel requires a version of the firmware greater than 1.9.14, very early versions of Anima Evo sabers shipped without any PC-communication, update your firmware to use any saber manager program. (See the updater opposite)

**Comment by GuitoonDev** [comment]
> 1. Double check that it is an Anima EVO - the EVO has an on/off switch on the outside - the original Anima has two small switches inside the pommel.

Yes, I can confirm my Anima has only one switch that can be seen on the outside.

So I will test the option 2.

Thanks for your answer

**Comment by GuitoonDev** [comment]
Updating framework is working ! Thanks ^^
